sudo: no
language: python
python: "3.5"

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_cache"

cache:
  directories:
    - pip_cache

install: pip install -r requirements-dev.txt --use-mirrors

before_script: python manage.py collectstatic --noinput -c

script: python manage.py test
