services: docker
env:
  global:
    - DOCKER_REGISTRY=registry.heroku.com
    - HEROKU_PROD_APP=standups
    - HEROKU_STAGE_APP=standupstage
    - HEROKU_PROC_TYPE=web
before_install:
  - docker -v
  - docker-compose -v
install: make build
script: make test-image
after_success: bin/deploy.sh
