services:
  - docker
  - postgres
env:
  global:
    - DOCKER_REGISTRY=registry.heroku.com
    - HEROKU_PROD_APP=standups
    - HEROKU_STAGE_APP=standupstage
    - HEROKU_PROC_TYPE=web
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
    - DATABASE_URL=postgres://postgres:@localhost/standup
cache:
  directories:
    - /home/travis/docker/
before_install:
  - docker -v
  - docker-compose -v
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> docker/standup_base
  - bin/travis-docker-cache.sh load
install: make build
before_script:
  - psql -c 'create database standup;' -U postgres
script:
  - make test-image
  - bin/travis-docker-cache.sh save
deploy:
  - provider: script
    script: bin/deploy.sh stage
    on:
      branch: master
      repo: mozilla/standup
  - provider: script
    script: bin/deploy.sh prod
    on:
      tags: true
      repo: mozilla/standup
notifications:
  irc: "irc.mozilla.org#standup"
